# Generated by Django 3.1.4 on 2021-01-22 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Post_Code', models.CharField(max_length=10)),
                ('Description', models.CharField(max_length=200)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Price', models.FloatField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Properties',
            },
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='myapp.property')),
                ('Floors', models.IntegerField(default=0)),
                ('Garden', models.BooleanField(default=False)),
                ('Furnised', models.BooleanField(default=False)),
                ('View', models.CharField(max_length=30)),
                ('Altitude', models.IntegerField(default=0)),
                ('Near_places', models.CharField(max_length=50)),
                ('Balconies', models.IntegerField(default=0)),
                ('Windows', models.IntegerField(default=0)),
                ('Light', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Details',
            },
        ),
    ]
