# Generated by Django 3.1.4 on 2021-02-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0002_auto_20210202_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='auth.user')),
                ('Phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
