# Generated by Django 3.1.4 on 2021-01-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210123_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Area',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Baths',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Garages',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
