# Generated by Django 3.1.4 on 2021-02-13 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Near_places',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
