# Generated by Django 3.1.4 on 2020-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Password1', models.CharField(max_length=100)),
                ('Password2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'NewUserRegister',
            },
        ),
    ]
