# Generated by Django 3.1.4 on 2020-12-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userregister'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregister',
            table='newuserregister',
        ),
    ]
