# Generated by Django 3.1.4 on 2020-12-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201207_2210'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregister',
            table='userregister',
        ),
    ]
