# Generated by Django 3.1.4 on 2020-12-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201207_2211'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregister',
            table='newuserregister',
        ),
    ]
