# Generated by Django 3.1.4 on 2020-12-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201207_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_insertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Properties',
            },
        ),
    ]
