# Generated by Django 3.1.4 on 2020-12-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_insertion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
