# Generated by Django 3.1.4 on 2020-12-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('user_insertion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.user_insertion')),
            ],
            bases=('myapp.user_insertion',),
        ),
    ]
