# Generated by Django 3.1.4 on 2020-12-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_insertion',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
