# Generated by Django 3.1.4 on 2020-12-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201229_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_insertion',
            name='user',
        ),
    ]
